### ISSUE TITLE
Hide window border setting counts for all latte lay outs 

### ISSUE THREAD

**Issue by begonia208** [psifidotos/applet-window-buttons#26]
SUMMARY
When the plasma applet window buttons https://github.com/psifidotos/applet-window-buttons is set to "hide window decoration when maximized" this setting is applied to all latte lay outs. Also ones where it is not wished.

STEPS TO REPRODUCE
1. activate the "applet window buttons" in one latte lay out and set it to hide the window decoration when the window is maximized
2. choose an other latte lay out where this applet is not applied to 
3. maximize the window of an application

OBSERVED RESULT
the window border disappears which is not desired.

EXPECTED RESULT
the window border will remain when the application is maximize because the whole applet shouldn't be of influence on latte lay outs where it is not applied to 

SOFTWARE/OS VERSIONS

Linux/KDE Plasma:
(available in About System)
KDE Plasma Version:  5.14.3
KDE Frameworks Version: 5.51.0
Qt Version: 5.11.12
plasma applet window buttons: 02

**Comment by psifidotos** [comment]
for Latte v0.8 this is your solution: https://github.com/psifidotos/Latte-Dock/wiki/F.A.Q.#q-latte-v08-deactivates-borderless-maximized-windows-from-active-window-control-plasmoid-what-can-i-do-

for Latte v0.9 this option wont be shown at all in Window Buttons applet because Latte is responsible to handle different borderless maximized windows settings per layout

**Comment by begonia208** [comment]
Your tip  https://github.com/psifidotos/Latte-Dock/wiki/F.A.Q.#q-latte-v08-deactivates-borderless-maximized-windows-from-active-window-control-plasmoid-what-can-i-do- worked like a charm! Thank you!
