### ISSUE TITLE
[Feature] Option to have titlebar buttons use Plasma Theme colours

### ISSUE THREAD

**Issue by feren** [psifidotos/applet-window-buttons#56]
It'd be nice to have the option to have the titlebar buttons use the Plasma Theme colours instead of the non-Aurorae titlebar theme's own titlebar colouring if possible. That'd make it easier for one to make it adaptable between light and dark Plasma Themes and for two would just make more sense to be honest having it follow the panel colours like all the other applets are on a panel.

Aurorae themes are obvious out of the equation for reference, here. Instead, I'm referring more to Breeze and its forks.

**Comment by psifidotos** [comment]
In what panel are you using it, Plasma or Latte?

**Comment by feren** [comment]
Traditional Plasma Panel

**Comment by psifidotos** [comment]
> Traditional Plasma Panel

Ok, what you are describing is not possible on applet level. Window Buttons Applets is NOT drawing any button at all. Button are drawing from their own implementation through the kdecoration2 library. The applet is only providing the space in which each button should be painted. 

Concerning window buttons painting, the buttons can be painted if there is a full color scheme to be given to them in order to be painted correctly. This is how its achieved with Latte. Latte since v0.9 can provide a specific color palette / color scheme in order to paint themselves. This is how applets are painting themselves based on the active window that is touching a Latte panel, paint themselves with reversed colors from the current plasma theme.

You can observe this through videos at:
https://www.youtube.com/watch?v=8hcfpWNLL2M
https://www.youtube.com/watch?v=3pL2WsBTU1c

So Window Buttons Applet is already ready to support the Latte Smart Coloring mechanisms

P.S. I was searching you at https://phabricator.kde.org/T7622 in order to discuss how you change and load layouts for Latte, in case I can help you more... For example I could give implement a way to import and load a layout on the fly through Latte dbus calls...

**Comment by feren** [comment]
Plasma Themes have their own color files where they can set their own colours for their themeing... is it not potentially possible to tap into this file for a colour scheme to draw the window buttons with?

**Comment by psifidotos** [comment]
Yes this is how Latte is providing the color scheme file after it has made adjustments to it. From my perspective this is Plasma responsibility and not applets. If more applets need this it shouldn't be applets trying to solve it but Plasma.

The Latte code can be observed at: https://github.com/KDE/latte-dock/blob/master/app/plasma/extended/theme.cpp

**Comment by psifidotos** [comment]
BTW why don't you try to import the color scheme from the Plasma theme into the KDE color schemes and set that one afterwards as the buttons color scheme?

**Comment by feren** [comment]
That probably wouldn't work so well for the transition between Feren OS and Feren OS Light Plasma Themes when the user manually applies them.

**Comment by feren** [comment]
But yeah, on thinking about it... given that your applet does already support colour scheme changing... is it not possible to make it call from the Plasma Theme's Colour Scheme too for colours as a colour scheme option without making it too complicated for even you to be able to maintain?

**Comment by psifidotos** [comment]
Tracking the current plasma theme and which one is its color scheme it is possible to implement but easy to maintain I am not that sure

**Comment by psifidotos** [comment]
![image](https://user-images.githubusercontent.com/2216474/67630896-16eea700-f897-11e9-9fdb-1a28eac39115.png)

**Comment by psifidotos** [comment]
added an option to support this but I still believe this should be plasma responsibility...

The fix contains also the Latte way to fix / workaround things.... many plasma theme color schemes do not provide the needed values in order to paint the buttons correctly... Latte solves this by enforcing the plasma theme background/textColor to buttons also.

**Comment by feren** [comment]
That option is well appreciated. Cheers for adding it.

The only downside I can see though with Latte, besides Plasma Shell's Desktop Grid issue, is that System Tray and Task Manager usually gets their icons filled over with a solid bout of the text colour with those alternative colouring options.

**Comment by psifidotos** [comment]
Latte taskmanager shouldn't have any issue with AutoColoring from Latte, you mean the plasma taskmanager?

The systray case can be solved from https://github.com/psifidotos/plasma-systray-Latte-Tweaks which gives the user options to choose which applets to be colored in the systray and which they should not. It gives also an option to set the applets spacing in the systray.

**Comment by feren** [comment]
Yeah, I was meaning Plasma Task Manager. Nice to see you thought ahead about the System Tray, though.

**Comment by psifidotos** [comment]
Yeah, the Latte AutoColoring is available to all plasma applets if they want to support it through qml... All available information can be found at https://techbase.kde.org/LatteDock
